gh: https://github.com/nsde
redirect: /
report: /contact

muse: https://muse.onlix.me
lino: https://lino.onlix.me
librenode: https://lino.onlix.me
status: https://stats.uptimerobot.com/BXg56HDW8W
bug-bounty: /legal#bug-bounty